package com.viajescarolina.api.home.application.dto;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;

public record HomeHeroDTO(
        Integer id,
        String badgeText,
        String titleHighlight,
        String titleAccent,
        String description,
        String whatsappCtaText,
        String whatsappMessageOverride,
        String secondaryCtaText,
        String secondaryCtaUrl,
        List<String> trustIndicators,
        Long backgroundMediaId,
        String backgroundMediaUrl,
        Double backgroundFocalX,
        Double backgroundFocalY,
        String featuredCardBadge,
        String featuredCardTitle,
        String featuredCardSubtitle,
        BigDecimal featuredCardPricePen,
        String featuredCardOrigin,
        Long featuredCardMediaId,
        String featuredCardMediaUrl,
        Long secondaryMedia1Id,
        String secondaryMedia1Url,
        Double secondaryMedia1FocalX,
        Double secondaryMedia1FocalY,
        Long secondaryMedia2Id,
        String secondaryMedia2Url,
        Double secondaryMedia2FocalX,
        Double secondaryMedia2FocalY,
        Long secondaryMedia3Id,
        String secondaryMedia3Url,
        Double secondaryMedia3FocalX,
        Double secondaryMedia3FocalY,
        Long secondaryMedia4Id,
        String secondaryMedia4Url,
        Double secondaryMedia4FocalX,
        Double secondaryMedia4FocalY,
        String trustStatText,
        String eyebrowText,
        Integer revision,
        Instant updatedAt
) {}
